local wezterm = require("wezterm")
local act = wezterm.action

local config = {
font = wezterm.font "RobotoMono Nerd Font Mono",
font_size = 14,
-- color_scheme = "Gruber (base16)",
-- color_scheme = "Hardcore",
-- color_scheme = "carbonfox",
color_scheme = "kanagawabones",
-- color_scheme = "Highway",
-- color_scheme = "zenburned",
-- color_scheme = "Gruvbox dark, soft (base16)",
-- color_scheme = "ChallengerDeep",
--default_prog = { "pwsh", "-nologo" },
inactive_pane_hsb = { saturation = 0.8, brightness = 0.5 },
window_decorations = "RESIZE",
window_padding = {left = 5, right = 0, top = 5, bottom = 0, },
tab_bar_at_bottom = true,
check_for_updates = false,
use_dead_keys = false,
animation_fps = 1,
cursor_blink_ease_in = 'Constant',
cursor_blink_ease_out = 'Constant',
initial_rows = 30,
initial_cols = 100,
disable_default_key_bindings = true,
  leader = { key='`', mods='ALT', timeout_milliseconds=1000 },
  keys = {
    { key = 'Tab', mods = 'CTRL', action = act.ActivateTabRelative(1) },
    { key = 'Tab', mods = 'SHIFT|CTRL', action = act.ActivateTabRelative(-1) },
    { key = 'Insert', mods = 'SHIFT', action = act.PasteFrom 'PrimarySelection' },
    { key = 'C', mods = 'SHIFT|CTRL', action = act.CopyTo 'Clipboard' },
    { key = 'V', mods = 'SHIFT|CTRL', action = act.PasteFrom 'Clipboard' },
    { key = '+', mods = 'SHIFT|CTRL', action = act.IncreaseFontSize },
    { key = '_', mods = 'SHIFT|CTRL', action = act.DecreaseFontSize },
    { key = ')', mods = 'SHIFT|CTRL', action = act.ResetFontSize },
    { key = 'R', mods = 'SHIFT|CTRL', action = act.ReloadConfiguration },
    { key = 'L', mods = 'SHIFT|CTRL', action = act.ShowDebugOverlay },
    { key = 'F1', mods = 'SHIFT', action = act.ActivateCommandPalette },
    { key = 'PageUp', mods = 'SHIFT', action = act.ScrollByPage(-1) },
    { key = 'PageDown', mods = 'SHIFT', action = act.ScrollByPage(1) },
    { key = '}', mods = 'LEADER|SHIFT', action = act.SplitVertical { domain = 'CurrentPaneDomain' }},
    { key = '{', mods = 'LEADER|SHIFT', action = act.SplitHorizontal { domain = 'CurrentPaneDomain' }},
    { key = '[', mods = 'LEADER', action = act.ActivatePaneDirection 'Prev' },
    { key = ']', mods = 'LEADER', action = act.ActivatePaneDirection 'Next' },
    { key = 'LeftArrow', mods = 'SHIFT', action = act.AdjustPaneSize{ 'Left', 1 } },
    { key = 'RightArrow', mods = 'SHIFT', action = act.AdjustPaneSize{ 'Right', 1 } },
    { key = 'UpArrow', mods = 'SHIFT', action = act.AdjustPaneSize{ 'Up', 1 } },
    { key = 'DownArrow', mods = 'SHIFT', action = act.AdjustPaneSize{ 'Down', 1 } },
    { key = 'N', mods = 'SHIFT|CTRL', action = act.SpawnWindow },
    { key = 'T', mods = 'SHIFT|CTRL', action = act.SpawnTab 'CurrentPaneDomain' },
    { key = 'w', mods = 'LEADER', action = act.CloseCurrentTab{ confirm = true } },
    { key = 'x', mods = 'ALT', action = act.CloseCurrentPane{ confirm = true } },
    { key = 'Z', mods = 'LEADER|SHIFT', action = act.TogglePaneZoomState },
  },
}



return config
